apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rostok-eks-cluster
  region: us-east-1
  version: "1.29"

nodeGroups:
  - name: ng-public-1
    instanceType: t3.medium
    desiredCapacity: 2
    amiFamily: AmazonLinux2
    labels: {role: worker}
    tags:
      Name: eks-worker-node-public
