

#грубо кажучи наприклад в нас є сайт користувач буде стукатися по посиланню на сайт, він першим ділом перейде на vm3 так як це публічний сервер потім vm3 відасть на загально доступний север де в нас код який обробить сторінку або застосує якийсь алгорит і щось нам видасть
#але в нас є приватний сервер тут мають лежати бази даних в яких зберігається інформація, тобто vm3 звертається до vm1 забирає потрібні данні з vm2 та виводить сторінку користувачу



###   ПРОХАННЯ ПОВІДОМИТИ ЯКЩО ЩОСЬ НЕ ВІРНО СКАЗАВ АБО СДОПОВНИТИ. ВЕЛЕЧЕЗНЕ ДЯКУЮ



Vagrant.configure("2") do |config| #Шапка створення 
    config.vm.box = "bento/ubuntu-24.04" #В усіх нижце віртуальних машин буде операційка яка прописана тут
  
    # =================================================================
    # 1. VM1: Загальнодоступний вебсервер (DHCP) 
    # =================================================================
    config.vm.define "vm1" do |subconfig| #Шапка віртуальної машини та її назва
      # Тут ведеться опиш віртуалки
      subconfig.vm.hostname = "webserver-vm1" #назва віртуалки яку ви будемо бачити кли в неї зайдемо
  
      subconfig.vm.network "public_network" #для зєднання з vm3


      subconfig.vm.network "private_network", ip: "192.168.56.10" #для зєднання з vm2
  
      subconfig.vm.synced_folder "./vm1", "/home/vagrant/test_vm1" # все лежить в папці яка прописана перша має зявитися те що прописано в другому
  
      subconfig.vm.provision "shell", inline: "echo 'vm1 done'" # виконується команда коли запустилася віртуалка
    end
  
    # =================================================================
    # 2. VM2: Приватний сервер (Static IP)
    # =================================================================
    config.vm.define "vm2" do |subconfig|
      subconfig.vm.hostname = "private-vm2"
  
      subconfig.vm.network "private_network", ip: "192.168.56.20" # приватний ip
  
      subconfig.vm.synced_folder "./vm2", "/home/vagrant/test_vm2"
  
      subconfig.vm.provision "shell", path: "vm2/script.sh" # виконується команда коли запустилася віртуалка
    end
  
    # =================================================================
    # 3. VM3: Публічний сервер (Static IP + Bridge) 
    # =================================================================
    config.vm.define "vm3" do |subconfig|
      subconfig.vm.hostname = "static-vm3"
  
      subconfig.vm.network "public_network", ip: "192.168.1.222", bridge: "wlp3s0" # прописуємо публічний ip та прописуєм мережеву карту(прописаний роутер)
  
      subconfig.vm.synced_folder "./vm3", "/home/vagrant/test_vm3"
  
      subconfig.vm.provision "shell", inline: "echo 'vm3 done'" # виконується команда коли запустилася віртуалка
    end
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" # ram
      vb.cpus = 1 # cpu
    end
  end