# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Загальний образ для всіх машин: Ubuntu 24.04
    config.vm.box = "bento/ubuntu-24.04"
  
    # =================================================================
    # 1. VM1: Загальнодоступний вебсервер (DHCP)
    # =================================================================
    config.vm.define "vm1" do |subconfig|
      subconfig.vm.hostname = "webserver-vm1"
  
      # Мережа: Публічна (отримає IP від роутера)
      subconfig.vm.network "public_network"
  
      # Спільна папка:
      # Ваша папка "./vm1" з'явиться всередині як "/home/vagrant/test_vm1"
      subconfig.vm.synced_folder "./vm1", "/home/vagrant/test_vm1"
  
      # Провізіонінг:
      subconfig.vm.provision "shell", inline: "echo 'vm1 done'"
    end
  
    # =================================================================
    # 2. VM2: Приватний сервер (Static IP)
    # =================================================================
    config.vm.define "vm2" do |subconfig|
      subconfig.vm.hostname = "private-vm2"
  
      # Мережа: Приватна (192.168.56.20)
      subconfig.vm.network "private_network", ip: "192.168.56.20"
  
      # Спільна папка:
      # Ваша папка "./vm2" з'явиться всередині як "/home/vagrant/test_vm2"
      subconfig.vm.synced_folder "./vm2", "/home/vagrant/test_vm2"
  
      # Провізіонінг через ваш скрипт
      subconfig.vm.provision "shell", path: "vm2/script.sh"
    end
  
    # =================================================================
    # 3. VM3: Публічний сервер (Static IP + Bridge)
    # =================================================================
    config.vm.define "vm3" do |subconfig|
      subconfig.vm.hostname = "static-vm3"
  
      # Мережа: Публічна зі статичним IP
      # 1. bridge: змініть "enp3s0" на ВАШ реальний адаптер (enp.../wlp...)
      # 2. ip: змініть, якщо ваша домашня мережа не 192.168.0.x
      subconfig.vm.network "public_network", ip: "192.168.1.222", bridge: "enp3s0"
  
      # Спільна папка:
      # Ваша папка "./vm3" з'явиться всередині як "/home/vagrant/test_vm3"
      subconfig.vm.synced_folder "./vm3", "/home/vagrant/test_vm3"
  
      subconfig.vm.provision "shell", inline: "echo 'vm3 done'"
    end
  
    # Обмеження ресурсів
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end