Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"

  # Доступ до сайту
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "VagrantVM_Nginx_Main"
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Запуск скрипта встановлення
  config.vm.provision "shell", path: "provision.sh"
end