Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"

  # Доступ до сайту
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "VagrantVM_Nginx_Main"
    vb.memory = "2048"
    vb.cpus = 2

    # Створюємо файл віртуального диска на 5 ГБ
    file_to_disk = "web_data.vdi" # пишемо змінну в якій зберігаємо назву фалу
    unless File.exist?(file_to_disk) # перевіряє чи файл не був створений так як якщо ви будемо перезапускати віртуалку воно захоче створити такий самий фал і буде видавати помилку так як він вже існує
      vb.customize ['createhd', '--filename', file_to_disk, '--size', 5120] # пряма команда для створення нового жорсткого диска (але вона ще не підключена до віртуальної машини)
    end

    # Ця команда каже візьми той фал який ми створили і встав його в порт віртуальної машини
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk] 
  end

  # Запуск скрипта встановлення
  config.vm.provision "shell", path: "provision.sh"
end