Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"

  # Доступ до сайту
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "VagrantVM_Full_Infra"
    vb.memory = "2048"
    vb.cpus = 2

    # Масив дисків для створення (Назва => Розмір у МБ)
    disks = {
      "web_data.vdi" => 5120,    # 5GB для сайту
      "db_data.vdi"  => 5120,    # 5GB для бази даних
      "backups.vdi"  => 10240    # 10GB для бекапів
    }

    disks.each_with_index do |(name, size), index|
      unless File.exist?(name)
        vb.customize ['createhd', '--filename', name, '--size', size]
      end
      # Порти SATA: 1, 2, 3 (Порт 0 зайнятий ОС)
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', 
                    '--port', index + 1, '--device', 0, '--type', 'hdd', '--medium', name]
    end
  end

  # Запуск скрипта встановлення
  config.vm.provision "shell", path: "provision.sh"
end